export const ORDER_BATCH_CONSTANTS = {
    BINANCE_TRADE_LIMIT: 1000,
    BINANCE_BATCH_SIZE: 5,
    BLOFIN_BATCH_SIZE: 20,
    BYBIT_BATCH_SIZE: 10,
} as const;

export const TWAP_CONSTANTS = {
    COMPLETED_DISPLAY_MS: 3000,
} as const;

export const TPSL_CONSTANTS = {
    DEFAULT_TP_OFFSET_PERCENT: 1.01,
    DEFAULT_SL_OFFSET_PERCENT: 0.99,
} as const;
